<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260830071752 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the review table with rating integrity and query indexes.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, company_name VARCHAR(255) NOT NULL, rating INT NOT NULL, review_text TEXT NOT NULL, author_email VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id), CONSTRAINT chk_review_rating CHECK (rating BETWEEN 1 AND 5))');
        $this->addSql('CREATE INDEX idx_review_company_name ON review (company_name)');
        $this->addSql('CREATE INDEX idx_review_created_at ON review (created_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE review');
    }
}
